n=int(input('So tien ban dau: '))
k=int(input('So thang gui: '))
T=float(input('Lai suat/thang: '))
print('Voi so tien ban dau',n,end=",")
print(' sau',k,'thang gui',end=",")
print(' lai suat ',T,'/ thang',sep="")
m=n*(1+k*T)
print('Thi so tien nhan duoc cuoi ky la:',m)